#region Copyright 2023 One Identity LLC.
/*
 * ONE IDENTITY LLC. PROPRIETARY INFORMATION
 *
 * This software is confidential.  One Identity, LLC. or one of its affiliates or
 * subsidiaries, has supplied this software to you under terms of a
 * license agreement, nondisclosure agreement or both.
 *
 * You may not copy, disclose, or use this software except in accordance with
 * those terms.
 *
 *
 * Copyright 2023 One Identity LLC.
 * ALL RIGHTS RESERVED.
 *
 * ONE IDENTITY LLC. MAKES NO REPRESENTATIONS OR
 * WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, OR
 * NON-INFRINGEMENT.  ONE IDENTITY LLC. SHALL NOT BE
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE
 * AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
 * THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */
#endregion

using NLog;
using QBM.CompositionApi.Definition;
using VI.Base.Logging;
using VI.WebRuntime.Data;

namespace QBM.CompositionApi.Sdk01_Basics
{
    public class Logging : IApiProvider
    {
        private static readonly NLog.Logger Logger = LogManager.GetLogger(LogNames.WebLog);

        public void Build(IApiBuilder builder)
        {
            builder.AddMethod(Method.Define("logging")
                .WithParameter("param", typeof(string))
                .HandleGet(qr =>
                {
                    var param = qr.Parameters.Get<string>("param");
                    if (string.IsNullOrEmpty(param))
                        param = "(no value)";

                    // By default, log messages generated by this sample will be written
                    // to %localappdata%\One Identity\One Identity Manager\imxclient\imxclient.log

                    // You can use the complete functionality of NLog.
                    // This is a very simple log message:
                    Logger.Info("This is a global log message. The client sent: " + param);

                    // For most scenarios that work with a database connection,
                    // it is recommended to log using the session ID, so that
                    // the log entries include this ID.
                    var sessionSpecificLogger = qr.Session.GetLogSession();
                    sessionSpecificLogger.Info("This is a session-specific log message. The client sent: " + param);

                    // Return something to the client
                    return "You sent the parameter: " + param;
                }));
        }
    }
}
